name: Slack - Github Action
description: A Github Action that sends custom Slack notifications by use of templates.
author: keithalpichi
inputs:
  template:
    description: The design template to use for the Slack notification. View the README for details of each template
    required: true
  title:
    description: The title to display on the Slack notification
    required: false
  description:
    description: The description to display on the Slack notification
    required: false
  status:
    description: Report success, failure, cancelled or a custom status
    required: false
  steps:
    description: Report on the status of individual steps
    required: false
  channel:
    description: Override default channel with different channel or username
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: mail
  color: orange