name: Release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false